---
name: CI
on:
  - push
  - pull_request
jobs:
  spec:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - "1.9.3"
          - "2.0.0"
          - "2.1"
          - "2.2"
          - "2.3"
        rails_version:
          - "3.0"
          - "3.1"
          - "3.2"
          - "4.0"
          - "4.1"
          - "4.2"
        include:
          - ruby_version: "2.4"
            rails_version: "4.2"
          - ruby_version: "2.5"
            rails_version: "4.2"
          - ruby_version: "2.2"
            rails_version: "5.0"
          - ruby_version: "2.3"
            rails_version: "5.0"
          - ruby_version: "2.4"
            rails_version: "5.0"
          - ruby_version: "2.5"
            rails_version: "5.0"
          - ruby_version: "2.2"
            rails_version: "5.1"
          - ruby_version: "2.3"
            rails_version: "5.1"
          - ruby_version: "2.4"
            rails_version: "5.1"
          - ruby_version: "2.5"
            rails_version: "5.1"
          - ruby_version: "2.2"
            rails_version: "5.2"
          - ruby_version: "2.3"
            rails_version: "5.2"
          - ruby_version: "2.4"
            rails_version: "5.2"
          - ruby_version: "2.5"
            rails_version: "5.2"
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler: 1
          bundler-cache: true
          cache-version: rails${{ matrix.rails_version }}
        env:
          RAILS_VERSION: "~> ${{ matrix.rails_version }}.0"
      - run: gem update --no-rdoc --no-ri --system 2.7.11
        if: ${{ matrix.ruby_version == '1.9.3' }}
      - run: bundle exec rake

  spec-ruby1_8_7:
    runs-on: ubuntu-20.04
    strategy:
      # fail-fast: false
      matrix:
        rails_version:
          - "3.0"
          - "3.1"
          - "3.2"
    steps:
      - uses: actions/checkout@v2
      - uses: docker://silvioq/ruby-1.8.7
        with:
          entrypoint: /bin/bash
          args: >
            -x -c "gem install bundler -v '~> 1.17'
            && bundle install
            && bundle exec rake"
        env:
          RAILS_VERSION: "~> ${{ matrix.rails_version }}.0"

  spec-ruby1_9_2:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        rails_version:
          - "3.0"
          - "3.1"
          - "3.2"
    steps:
      - uses: actions/checkout@v2
      - run: wget https://rubygems.org/rubygems/rubygems-2.7.11.tgz
      - run: tar -xzf rubygems-2.7.11.tgz
      - uses: docker://allenwei/ruby-1.9.2
        with:
          entrypoint: /bin/bash
          args: >
            -x -c "unset GEM_HOME
            && cd rubygems-2.7.11
            && ruby setup.rb --no-document --silent
            && cd ..
            && gem install --no-document bundler -v '~> 1.17'
            && bundle install
            && bundle exec rake"
        env:
          RAILS_VERSION: "~> ${{ matrix.rails_version }}.0"
